# Generated by Django 3.2 on 2023-01-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pure_weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
