# Generated by Django 3.2 on 2023-02-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_pure_weight_product_package_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_ar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
