# Generated by Django 3.2 on 2023-02-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230214_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
